#!/usr/bin/python3

#Import-ant Libraries
import discord
from time import time
from data.data import BotData as data
from dotenv import load_dotenv
from os import environ

# Setup
boot_time = time()
bot = discord.Bot(intents = data.intents, owner_id = data.owner_id)

@bot.listen()
async def on_connect():

    await bot.change_presence(
        activity = discord.Game(data.activity),
        status = discord.Status.online)

    print(f'{bot.user.name} woke up in {time() - boot_time} seconds.')
    return


# Run
#bot.load_extensions('cogs')
load_dotenv()
bot.run(environ.get("TOKEN"))
