#!/usr/bin/python3

#Import-ant Libraries
from discord import Bot, Game
from time import time
import data.data as data
from dotenv import load_dotenv
from os import environ

#Variables
boot_time = time()
bot = Bot(intents = data.intents, owner_id = data.owner_id)


#Functions
@bot.listen()
async def on_connect():

	await bot.change_presence(activity = Game(data.activity))
	print(f'{bot.user.name} woke up in {time() - boot_time} seconds.')

	# tests_checklist = {
	# 	'Location Tests' : [
	# 			#('Delete Location', 'the-gardens'),
	# 			('Create Location', 'the-gardens'),
	# 			('Create Location', 'the-courtyard'),
	# 			('Create Character', ('Cylian', 'the-courtyard')),
	# 			('Create Character', ('Theo', 'the-gardens')),
	# 			('Create Location', 'the-village-outskirts'),
	# 			#('Delete Location', 'the-courtyard'),
	# 			#('Delete Location', 'the-village-outskirts'),
	# 			('Create Path', ('the-courtyard', 'the-gardens')),
	# 			('Create Path', ('the-courtyard', 'the-village-outskirts')
	# 			)
	# 		]
	# 	}

	#test_guild = await bot.fetch_guild(1114005940392439899)

	#from libraries.classes import Character
	#my_guy = Character(1196173831610564708)
	#from helpers.tests import tests
	#await tests(tests_checklist, test_guild)

	#print('Exiting.')
	#exit()

	return


#Run
bot.load_extensions('cogs')
load_dotenv()
bot.run(environ.get(("TOKEN"))
